package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AnioLectivo generated by hbm2java
 */
public class AnioLectivo  implements java.io.Serializable {


     private int anioLectivoId;
     private Serializable anioLectivoNombre;
     private boolean anioLectivoActivo;
     private Date anioLectivoFechaModificacion;
     private Set<ConfiguracionGrado> configuracionGrados = new HashSet<ConfiguracionGrado>(0);
     private Set<InstitucionParametro> institucionParametros = new HashSet<InstitucionParametro>(0);

    public AnioLectivo() {
    }

	
    public AnioLectivo(int anioLectivoId, Serializable anioLectivoNombre, boolean anioLectivoActivo, Date anioLectivoFechaModificacion) {
        this.anioLectivoId = anioLectivoId;
        this.anioLectivoNombre = anioLectivoNombre;
        this.anioLectivoActivo = anioLectivoActivo;
        this.anioLectivoFechaModificacion = anioLectivoFechaModificacion;
    }
    public AnioLectivo(int anioLectivoId, Serializable anioLectivoNombre, boolean anioLectivoActivo, Date anioLectivoFechaModificacion, Set<ConfiguracionGrado> configuracionGrados, Set<InstitucionParametro> institucionParametros) {
       this.anioLectivoId = anioLectivoId;
       this.anioLectivoNombre = anioLectivoNombre;
       this.anioLectivoActivo = anioLectivoActivo;
       this.anioLectivoFechaModificacion = anioLectivoFechaModificacion;
       this.configuracionGrados = configuracionGrados;
       this.institucionParametros = institucionParametros;
    }
   
    public int getAnioLectivoId() {
        return this.anioLectivoId;
    }
    
    public void setAnioLectivoId(int anioLectivoId) {
        this.anioLectivoId = anioLectivoId;
    }
    public Serializable getAnioLectivoNombre() {
        return this.anioLectivoNombre;
    }
    
    public void setAnioLectivoNombre(Serializable anioLectivoNombre) {
        this.anioLectivoNombre = anioLectivoNombre;
    }
    public boolean isAnioLectivoActivo() {
        return this.anioLectivoActivo;
    }
    
    public void setAnioLectivoActivo(boolean anioLectivoActivo) {
        this.anioLectivoActivo = anioLectivoActivo;
    }
    public Date getAnioLectivoFechaModificacion() {
        return this.anioLectivoFechaModificacion;
    }
    
    public void setAnioLectivoFechaModificacion(Date anioLectivoFechaModificacion) {
        this.anioLectivoFechaModificacion = anioLectivoFechaModificacion;
    }
    public Set<ConfiguracionGrado> getConfiguracionGrados() {
        return this.configuracionGrados;
    }
    
    public void setConfiguracionGrados(Set<ConfiguracionGrado> configuracionGrados) {
        this.configuracionGrados = configuracionGrados;
    }
    public Set<InstitucionParametro> getInstitucionParametros() {
        return this.institucionParametros;
    }
    
    public void setInstitucionParametros(Set<InstitucionParametro> institucionParametros) {
        this.institucionParametros = institucionParametros;
    }




}


