package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Arancel generated by hbm2java
 */
public class Arancel  implements java.io.Serializable {


     private int arancelId;
     private Serializable cod;
     private Serializable arancelNombre;
     private Serializable arancelAlias;
     private Boolean arancelMostrarInforme;
     private boolean arancelActivo;
     private Date arancelFechaModificacion;
     private Set<ArancelMatricula> arancelMatriculas = new HashSet<ArancelMatricula>(0);
     private Set<ControlPago> controlPagos = new HashSet<ControlPago>(0);

    public Arancel() {
    }

	
    public Arancel(int arancelId, Serializable arancelNombre, boolean arancelActivo, Date arancelFechaModificacion) {
        this.arancelId = arancelId;
        this.arancelNombre = arancelNombre;
        this.arancelActivo = arancelActivo;
        this.arancelFechaModificacion = arancelFechaModificacion;
    }
    public Arancel(int arancelId, Serializable cod, Serializable arancelNombre, Serializable arancelAlias, Boolean arancelMostrarInforme, boolean arancelActivo, Date arancelFechaModificacion, Set<ArancelMatricula> arancelMatriculas, Set<ControlPago> controlPagos) {
       this.arancelId = arancelId;
       this.cod = cod;
       this.arancelNombre = arancelNombre;
       this.arancelAlias = arancelAlias;
       this.arancelMostrarInforme = arancelMostrarInforme;
       this.arancelActivo = arancelActivo;
       this.arancelFechaModificacion = arancelFechaModificacion;
       this.arancelMatriculas = arancelMatriculas;
       this.controlPagos = controlPagos;
    }
   
    public int getArancelId() {
        return this.arancelId;
    }
    
    public void setArancelId(int arancelId) {
        this.arancelId = arancelId;
    }
    public Serializable getCod() {
        return this.cod;
    }
    
    public void setCod(Serializable cod) {
        this.cod = cod;
    }
    public Serializable getArancelNombre() {
        return this.arancelNombre;
    }
    
    public void setArancelNombre(Serializable arancelNombre) {
        this.arancelNombre = arancelNombre;
    }
    public Serializable getArancelAlias() {
        return this.arancelAlias;
    }
    
    public void setArancelAlias(Serializable arancelAlias) {
        this.arancelAlias = arancelAlias;
    }
    public Boolean getArancelMostrarInforme() {
        return this.arancelMostrarInforme;
    }
    
    public void setArancelMostrarInforme(Boolean arancelMostrarInforme) {
        this.arancelMostrarInforme = arancelMostrarInforme;
    }
    public boolean isArancelActivo() {
        return this.arancelActivo;
    }
    
    public void setArancelActivo(boolean arancelActivo) {
        this.arancelActivo = arancelActivo;
    }
    public Date getArancelFechaModificacion() {
        return this.arancelFechaModificacion;
    }
    
    public void setArancelFechaModificacion(Date arancelFechaModificacion) {
        this.arancelFechaModificacion = arancelFechaModificacion;
    }
    public Set<ArancelMatricula> getArancelMatriculas() {
        return this.arancelMatriculas;
    }
    
    public void setArancelMatriculas(Set<ArancelMatricula> arancelMatriculas) {
        this.arancelMatriculas = arancelMatriculas;
    }
    public Set<ControlPago> getControlPagos() {
        return this.controlPagos;
    }
    
    public void setControlPagos(Set<ControlPago> controlPagos) {
        this.controlPagos = controlPagos;
    }




}


