package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ArancelMatricula generated by hbm2java
 */
public class ArancelMatricula  implements java.io.Serializable {


     private int arancelMatriculaId;
     private Arancel arancel;
     private Matricula matricula;
     private Usuario usuario;
     private BigDecimal arancelValorInicial;
     private BigDecimal arancelValorActual;
     private Date arancelFechaCrea;
     private Date arancelFechaModificacion;
     private boolean arancelMatriculaActivo;

    public ArancelMatricula() {
    }

    public ArancelMatricula(int arancelMatriculaId, Arancel arancel, Matricula matricula, Usuario usuario, BigDecimal arancelValorInicial, BigDecimal arancelValorActual, Date arancelFechaCrea, Date arancelFechaModificacion, boolean arancelMatriculaActivo) {
       this.arancelMatriculaId = arancelMatriculaId;
       this.arancel = arancel;
       this.matricula = matricula;
       this.usuario = usuario;
       this.arancelValorInicial = arancelValorInicial;
       this.arancelValorActual = arancelValorActual;
       this.arancelFechaCrea = arancelFechaCrea;
       this.arancelFechaModificacion = arancelFechaModificacion;
       this.arancelMatriculaActivo = arancelMatriculaActivo;
    }
   
    public int getArancelMatriculaId() {
        return this.arancelMatriculaId;
    }
    
    public void setArancelMatriculaId(int arancelMatriculaId) {
        this.arancelMatriculaId = arancelMatriculaId;
    }
    public Arancel getArancel() {
        return this.arancel;
    }
    
    public void setArancel(Arancel arancel) {
        this.arancel = arancel;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public BigDecimal getArancelValorInicial() {
        return this.arancelValorInicial;
    }
    
    public void setArancelValorInicial(BigDecimal arancelValorInicial) {
        this.arancelValorInicial = arancelValorInicial;
    }
    public BigDecimal getArancelValorActual() {
        return this.arancelValorActual;
    }
    
    public void setArancelValorActual(BigDecimal arancelValorActual) {
        this.arancelValorActual = arancelValorActual;
    }
    public Date getArancelFechaCrea() {
        return this.arancelFechaCrea;
    }
    
    public void setArancelFechaCrea(Date arancelFechaCrea) {
        this.arancelFechaCrea = arancelFechaCrea;
    }
    public Date getArancelFechaModificacion() {
        return this.arancelFechaModificacion;
    }
    
    public void setArancelFechaModificacion(Date arancelFechaModificacion) {
        this.arancelFechaModificacion = arancelFechaModificacion;
    }
    public boolean isArancelMatriculaActivo() {
        return this.arancelMatriculaActivo;
    }
    
    public void setArancelMatriculaActivo(boolean arancelMatriculaActivo) {
        this.arancelMatriculaActivo = arancelMatriculaActivo;
    }




}


