package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * CambiosArancel generated by hbm2java
 */
public class CambiosArancel  implements java.io.Serializable {


     private int cambiosArancelesId;
     private ControlPago controlPago;
     private BigDecimal cambiosArancelValorInicial;
     private BigDecimal cambiosArancelValorFinal;
     private Serializable cambiosArancelObservación;
     private Date cambiosArancelFechaModificacion;
     private boolean cambiosArancelFechaModificacionActivo;

    public CambiosArancel() {
    }

    public CambiosArancel(int cambiosArancelesId, ControlPago controlPago, BigDecimal cambiosArancelValorInicial, BigDecimal cambiosArancelValorFinal, Serializable cambiosArancelObservación, Date cambiosArancelFechaModificacion, boolean cambiosArancelFechaModificacionActivo) {
       this.cambiosArancelesId = cambiosArancelesId;
       this.controlPago = controlPago;
       this.cambiosArancelValorInicial = cambiosArancelValorInicial;
       this.cambiosArancelValorFinal = cambiosArancelValorFinal;
       this.cambiosArancelObservación = cambiosArancelObservación;
       this.cambiosArancelFechaModificacion = cambiosArancelFechaModificacion;
       this.cambiosArancelFechaModificacionActivo = cambiosArancelFechaModificacionActivo;
    }
   
    public int getCambiosArancelesId() {
        return this.cambiosArancelesId;
    }
    
    public void setCambiosArancelesId(int cambiosArancelesId) {
        this.cambiosArancelesId = cambiosArancelesId;
    }
    public ControlPago getControlPago() {
        return this.controlPago;
    }
    
    public void setControlPago(ControlPago controlPago) {
        this.controlPago = controlPago;
    }
    public BigDecimal getCambiosArancelValorInicial() {
        return this.cambiosArancelValorInicial;
    }
    
    public void setCambiosArancelValorInicial(BigDecimal cambiosArancelValorInicial) {
        this.cambiosArancelValorInicial = cambiosArancelValorInicial;
    }
    public BigDecimal getCambiosArancelValorFinal() {
        return this.cambiosArancelValorFinal;
    }
    
    public void setCambiosArancelValorFinal(BigDecimal cambiosArancelValorFinal) {
        this.cambiosArancelValorFinal = cambiosArancelValorFinal;
    }
    public Serializable getCambiosArancelObservación() {
        return this.cambiosArancelObservación;
    }
    
    public void setCambiosArancelObservación(Serializable cambiosArancelObservación) {
        this.cambiosArancelObservación = cambiosArancelObservación;
    }
    public Date getCambiosArancelFechaModificacion() {
        return this.cambiosArancelFechaModificacion;
    }
    
    public void setCambiosArancelFechaModificacion(Date cambiosArancelFechaModificacion) {
        this.cambiosArancelFechaModificacion = cambiosArancelFechaModificacion;
    }
    public boolean isCambiosArancelFechaModificacionActivo() {
        return this.cambiosArancelFechaModificacionActivo;
    }
    
    public void setCambiosArancelFechaModificacionActivo(boolean cambiosArancelFechaModificacionActivo) {
        this.cambiosArancelFechaModificacionActivo = cambiosArancelFechaModificacionActivo;
    }




}


