package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ConfiguracionGrado generated by hbm2java
 */
public class ConfiguracionGrado  implements java.io.Serializable {


     private int configuracionGradoId;
     private AnioLectivo anioLectivo;
     private EspecialidadGrado especialidadGrado;
     private Grado grado;
     private String configuracionGradoSeccion;
     private boolean configuracionGradoActivo;
     private Date configuracionGradoFechaModificacion;
     private Set<Matricula> matriculas = new HashSet<Matricula>(0);

    public ConfiguracionGrado() {
    }

	
    public ConfiguracionGrado(int configuracionGradoId, AnioLectivo anioLectivo, EspecialidadGrado especialidadGrado, Grado grado, String configuracionGradoSeccion, boolean configuracionGradoActivo, Date configuracionGradoFechaModificacion) {
        this.configuracionGradoId = configuracionGradoId;
        this.anioLectivo = anioLectivo;
        this.especialidadGrado = especialidadGrado;
        this.grado = grado;
        this.configuracionGradoSeccion = configuracionGradoSeccion;
        this.configuracionGradoActivo = configuracionGradoActivo;
        this.configuracionGradoFechaModificacion = configuracionGradoFechaModificacion;
    }
    public ConfiguracionGrado(int configuracionGradoId, AnioLectivo anioLectivo, EspecialidadGrado especialidadGrado, Grado grado, String configuracionGradoSeccion, boolean configuracionGradoActivo, Date configuracionGradoFechaModificacion, Set<Matricula> matriculas) {
       this.configuracionGradoId = configuracionGradoId;
       this.anioLectivo = anioLectivo;
       this.especialidadGrado = especialidadGrado;
       this.grado = grado;
       this.configuracionGradoSeccion = configuracionGradoSeccion;
       this.configuracionGradoActivo = configuracionGradoActivo;
       this.configuracionGradoFechaModificacion = configuracionGradoFechaModificacion;
       this.matriculas = matriculas;
    }
   
    public int getConfiguracionGradoId() {
        return this.configuracionGradoId;
    }
    
    public void setConfiguracionGradoId(int configuracionGradoId) {
        this.configuracionGradoId = configuracionGradoId;
    }
    public AnioLectivo getAnioLectivo() {
        return this.anioLectivo;
    }
    
    public void setAnioLectivo(AnioLectivo anioLectivo) {
        this.anioLectivo = anioLectivo;
    }
    public EspecialidadGrado getEspecialidadGrado() {
        return this.especialidadGrado;
    }
    
    public void setEspecialidadGrado(EspecialidadGrado especialidadGrado) {
        this.especialidadGrado = especialidadGrado;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public String getConfiguracionGradoSeccion() {
        return this.configuracionGradoSeccion;
    }
    
    public void setConfiguracionGradoSeccion(String configuracionGradoSeccion) {
        this.configuracionGradoSeccion = configuracionGradoSeccion;
    }
    public boolean isConfiguracionGradoActivo() {
        return this.configuracionGradoActivo;
    }
    
    public void setConfiguracionGradoActivo(boolean configuracionGradoActivo) {
        this.configuracionGradoActivo = configuracionGradoActivo;
    }
    public Date getConfiguracionGradoFechaModificacion() {
        return this.configuracionGradoFechaModificacion;
    }
    
    public void setConfiguracionGradoFechaModificacion(Date configuracionGradoFechaModificacion) {
        this.configuracionGradoFechaModificacion = configuracionGradoFechaModificacion;
    }
    public Set<Matricula> getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set<Matricula> matriculas) {
        this.matriculas = matriculas;
    }




}


