package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ControlPago generated by hbm2java
 */
public class ControlPago  implements java.io.Serializable {


     private int controlPagoId;
     private Arancel arancel;
     private EstadoControlPago estadoControlPago;
     private Matricula matricula;
     private Usuario usuario;
     private Date controlPagoFechaIngresoPago;
     private BigDecimal controlPagoArancelAsignado;
     private BigDecimal controlPagoArancelPagado;
     private boolean controlPagoPagadoEnColegio;
     private boolean controlPagoMora;
     private Serializable controlPagoObservacion;
     private boolean controlPagoActivo;
     private Date controlPagoFechaModificacion;
     private Set<CambiosArancel> cambiosArancels = new HashSet<CambiosArancel>(0);
     private Set<DetalleControlReversion> detalleControlReversions = new HashSet<DetalleControlReversion>(0);
     private Set<DetalleControlPago> detalleControlPagos = new HashSet<DetalleControlPago>(0);
     private Set<DetalleAsignacionCuota> detalleAsignacionCuotas = new HashSet<DetalleAsignacionCuota>(0);

    public ControlPago() {
    }

	
    public ControlPago(int controlPagoId, Arancel arancel, EstadoControlPago estadoControlPago, Matricula matricula, Usuario usuario, Date controlPagoFechaIngresoPago, boolean controlPagoPagadoEnColegio, boolean controlPagoMora, Serializable controlPagoObservacion, boolean controlPagoActivo, Date controlPagoFechaModificacion) {
        this.controlPagoId = controlPagoId;
        this.arancel = arancel;
        this.estadoControlPago = estadoControlPago;
        this.matricula = matricula;
        this.usuario = usuario;
        this.controlPagoFechaIngresoPago = controlPagoFechaIngresoPago;
        this.controlPagoPagadoEnColegio = controlPagoPagadoEnColegio;
        this.controlPagoMora = controlPagoMora;
        this.controlPagoObservacion = controlPagoObservacion;
        this.controlPagoActivo = controlPagoActivo;
        this.controlPagoFechaModificacion = controlPagoFechaModificacion;
    }
    public ControlPago(int controlPagoId, Arancel arancel, EstadoControlPago estadoControlPago, Matricula matricula, Usuario usuario, Date controlPagoFechaIngresoPago, BigDecimal controlPagoArancelAsignado, BigDecimal controlPagoArancelPagado, boolean controlPagoPagadoEnColegio, boolean controlPagoMora, Serializable controlPagoObservacion, boolean controlPagoActivo, Date controlPagoFechaModificacion, Set<CambiosArancel> cambiosArancels, Set<DetalleControlReversion> detalleControlReversions, Set<DetalleControlPago> detalleControlPagos, Set<DetalleAsignacionCuota> detalleAsignacionCuotas) {
       this.controlPagoId = controlPagoId;
       this.arancel = arancel;
       this.estadoControlPago = estadoControlPago;
       this.matricula = matricula;
       this.usuario = usuario;
       this.controlPagoFechaIngresoPago = controlPagoFechaIngresoPago;
       this.controlPagoArancelAsignado = controlPagoArancelAsignado;
       this.controlPagoArancelPagado = controlPagoArancelPagado;
       this.controlPagoPagadoEnColegio = controlPagoPagadoEnColegio;
       this.controlPagoMora = controlPagoMora;
       this.controlPagoObservacion = controlPagoObservacion;
       this.controlPagoActivo = controlPagoActivo;
       this.controlPagoFechaModificacion = controlPagoFechaModificacion;
       this.cambiosArancels = cambiosArancels;
       this.detalleControlReversions = detalleControlReversions;
       this.detalleControlPagos = detalleControlPagos;
       this.detalleAsignacionCuotas = detalleAsignacionCuotas;
    }
   
    public int getControlPagoId() {
        return this.controlPagoId;
    }
    
    public void setControlPagoId(int controlPagoId) {
        this.controlPagoId = controlPagoId;
    }
    public Arancel getArancel() {
        return this.arancel;
    }
    
    public void setArancel(Arancel arancel) {
        this.arancel = arancel;
    }
    public EstadoControlPago getEstadoControlPago() {
        return this.estadoControlPago;
    }
    
    public void setEstadoControlPago(EstadoControlPago estadoControlPago) {
        this.estadoControlPago = estadoControlPago;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getControlPagoFechaIngresoPago() {
        return this.controlPagoFechaIngresoPago;
    }
    
    public void setControlPagoFechaIngresoPago(Date controlPagoFechaIngresoPago) {
        this.controlPagoFechaIngresoPago = controlPagoFechaIngresoPago;
    }
    public BigDecimal getControlPagoArancelAsignado() {
        return this.controlPagoArancelAsignado;
    }
    
    public void setControlPagoArancelAsignado(BigDecimal controlPagoArancelAsignado) {
        this.controlPagoArancelAsignado = controlPagoArancelAsignado;
    }
    public BigDecimal getControlPagoArancelPagado() {
        return this.controlPagoArancelPagado;
    }
    
    public void setControlPagoArancelPagado(BigDecimal controlPagoArancelPagado) {
        this.controlPagoArancelPagado = controlPagoArancelPagado;
    }
    public boolean isControlPagoPagadoEnColegio() {
        return this.controlPagoPagadoEnColegio;
    }
    
    public void setControlPagoPagadoEnColegio(boolean controlPagoPagadoEnColegio) {
        this.controlPagoPagadoEnColegio = controlPagoPagadoEnColegio;
    }
    public boolean isControlPagoMora() {
        return this.controlPagoMora;
    }
    
    public void setControlPagoMora(boolean controlPagoMora) {
        this.controlPagoMora = controlPagoMora;
    }
    public Serializable getControlPagoObservacion() {
        return this.controlPagoObservacion;
    }
    
    public void setControlPagoObservacion(Serializable controlPagoObservacion) {
        this.controlPagoObservacion = controlPagoObservacion;
    }
    public boolean isControlPagoActivo() {
        return this.controlPagoActivo;
    }
    
    public void setControlPagoActivo(boolean controlPagoActivo) {
        this.controlPagoActivo = controlPagoActivo;
    }
    public Date getControlPagoFechaModificacion() {
        return this.controlPagoFechaModificacion;
    }
    
    public void setControlPagoFechaModificacion(Date controlPagoFechaModificacion) {
        this.controlPagoFechaModificacion = controlPagoFechaModificacion;
    }
    public Set<CambiosArancel> getCambiosArancels() {
        return this.cambiosArancels;
    }
    
    public void setCambiosArancels(Set<CambiosArancel> cambiosArancels) {
        this.cambiosArancels = cambiosArancels;
    }
    public Set<DetalleControlReversion> getDetalleControlReversions() {
        return this.detalleControlReversions;
    }
    
    public void setDetalleControlReversions(Set<DetalleControlReversion> detalleControlReversions) {
        this.detalleControlReversions = detalleControlReversions;
    }
    public Set<DetalleControlPago> getDetalleControlPagos() {
        return this.detalleControlPagos;
    }
    
    public void setDetalleControlPagos(Set<DetalleControlPago> detalleControlPagos) {
        this.detalleControlPagos = detalleControlPagos;
    }
    public Set<DetalleAsignacionCuota> getDetalleAsignacionCuotas() {
        return this.detalleAsignacionCuotas;
    }
    
    public void setDetalleAsignacionCuotas(Set<DetalleAsignacionCuota> detalleAsignacionCuotas) {
        this.detalleAsignacionCuotas = detalleAsignacionCuotas;
    }




}


