package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * DetalleAsignacionCuota generated by hbm2java
 */
public class DetalleAsignacionCuota  implements java.io.Serializable {


     private int detalleAsginacionCuotaId;
     private ControlPago controlPago;
     private Usuario usuario;
     private BigDecimal detalleAsignacionCuotaAnterior;
     private BigDecimal detalleAsignacionCuotaNueva;
     private Serializable detalleAsignacionCuotaObservacion;
     private boolean detalleAsignacionCuotaActivo;
     private Date detalleAsignacionCuotaFecha;

    public DetalleAsignacionCuota() {
    }

    public DetalleAsignacionCuota(int detalleAsginacionCuotaId, ControlPago controlPago, Usuario usuario, BigDecimal detalleAsignacionCuotaAnterior, BigDecimal detalleAsignacionCuotaNueva, Serializable detalleAsignacionCuotaObservacion, boolean detalleAsignacionCuotaActivo, Date detalleAsignacionCuotaFecha) {
       this.detalleAsginacionCuotaId = detalleAsginacionCuotaId;
       this.controlPago = controlPago;
       this.usuario = usuario;
       this.detalleAsignacionCuotaAnterior = detalleAsignacionCuotaAnterior;
       this.detalleAsignacionCuotaNueva = detalleAsignacionCuotaNueva;
       this.detalleAsignacionCuotaObservacion = detalleAsignacionCuotaObservacion;
       this.detalleAsignacionCuotaActivo = detalleAsignacionCuotaActivo;
       this.detalleAsignacionCuotaFecha = detalleAsignacionCuotaFecha;
    }
   
    public int getDetalleAsginacionCuotaId() {
        return this.detalleAsginacionCuotaId;
    }
    
    public void setDetalleAsginacionCuotaId(int detalleAsginacionCuotaId) {
        this.detalleAsginacionCuotaId = detalleAsginacionCuotaId;
    }
    public ControlPago getControlPago() {
        return this.controlPago;
    }
    
    public void setControlPago(ControlPago controlPago) {
        this.controlPago = controlPago;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public BigDecimal getDetalleAsignacionCuotaAnterior() {
        return this.detalleAsignacionCuotaAnterior;
    }
    
    public void setDetalleAsignacionCuotaAnterior(BigDecimal detalleAsignacionCuotaAnterior) {
        this.detalleAsignacionCuotaAnterior = detalleAsignacionCuotaAnterior;
    }
    public BigDecimal getDetalleAsignacionCuotaNueva() {
        return this.detalleAsignacionCuotaNueva;
    }
    
    public void setDetalleAsignacionCuotaNueva(BigDecimal detalleAsignacionCuotaNueva) {
        this.detalleAsignacionCuotaNueva = detalleAsignacionCuotaNueva;
    }
    public Serializable getDetalleAsignacionCuotaObservacion() {
        return this.detalleAsignacionCuotaObservacion;
    }
    
    public void setDetalleAsignacionCuotaObservacion(Serializable detalleAsignacionCuotaObservacion) {
        this.detalleAsignacionCuotaObservacion = detalleAsignacionCuotaObservacion;
    }
    public boolean isDetalleAsignacionCuotaActivo() {
        return this.detalleAsignacionCuotaActivo;
    }
    
    public void setDetalleAsignacionCuotaActivo(boolean detalleAsignacionCuotaActivo) {
        this.detalleAsignacionCuotaActivo = detalleAsignacionCuotaActivo;
    }
    public Date getDetalleAsignacionCuotaFecha() {
        return this.detalleAsignacionCuotaFecha;
    }
    
    public void setDetalleAsignacionCuotaFecha(Date detalleAsignacionCuotaFecha) {
        this.detalleAsignacionCuotaFecha = detalleAsignacionCuotaFecha;
    }




}


