package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * DetalleControlPago generated by hbm2java
 */
public class DetalleControlPago  implements java.io.Serializable {


     private int detalleControlPagoId;
     private ControlPago controlPago;
     private BigDecimal detalleControlPagoAbono;
     private Date detalleControlPagoAbonoFechaHora;
     private boolean detalleControlPagoEnColegio;

    public DetalleControlPago() {
    }

    public DetalleControlPago(int detalleControlPagoId, ControlPago controlPago, BigDecimal detalleControlPagoAbono, Date detalleControlPagoAbonoFechaHora, boolean detalleControlPagoEnColegio) {
       this.detalleControlPagoId = detalleControlPagoId;
       this.controlPago = controlPago;
       this.detalleControlPagoAbono = detalleControlPagoAbono;
       this.detalleControlPagoAbonoFechaHora = detalleControlPagoAbonoFechaHora;
       this.detalleControlPagoEnColegio = detalleControlPagoEnColegio;
    }
   
    public int getDetalleControlPagoId() {
        return this.detalleControlPagoId;
    }
    
    public void setDetalleControlPagoId(int detalleControlPagoId) {
        this.detalleControlPagoId = detalleControlPagoId;
    }
    public ControlPago getControlPago() {
        return this.controlPago;
    }
    
    public void setControlPago(ControlPago controlPago) {
        this.controlPago = controlPago;
    }
    public BigDecimal getDetalleControlPagoAbono() {
        return this.detalleControlPagoAbono;
    }
    
    public void setDetalleControlPagoAbono(BigDecimal detalleControlPagoAbono) {
        this.detalleControlPagoAbono = detalleControlPagoAbono;
    }
    public Date getDetalleControlPagoAbonoFechaHora() {
        return this.detalleControlPagoAbonoFechaHora;
    }
    
    public void setDetalleControlPagoAbonoFechaHora(Date detalleControlPagoAbonoFechaHora) {
        this.detalleControlPagoAbonoFechaHora = detalleControlPagoAbonoFechaHora;
    }
    public boolean isDetalleControlPagoEnColegio() {
        return this.detalleControlPagoEnColegio;
    }
    
    public void setDetalleControlPagoEnColegio(boolean detalleControlPagoEnColegio) {
        this.detalleControlPagoEnColegio = detalleControlPagoEnColegio;
    }




}


