package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * DetalleControlReversion generated by hbm2java
 */
public class DetalleControlReversion  implements java.io.Serializable {


     private int detalleControlReversionId;
     private ControlPago controlPago;
     private BigDecimal detalleControlReversionPagoAnterior;
     private BigDecimal detalleControlReversionPagoNuevo;
     private Date detalleControlReversionFechaHora;
     private boolean detalleControlReversionPagoEnColegio;
     private String detalleControlReversionPagoObservacion;
     private boolean detalleControlReversionPagoActivo;

    public DetalleControlReversion() {
    }

    public DetalleControlReversion(int detalleControlReversionId, ControlPago controlPago, BigDecimal detalleControlReversionPagoAnterior, BigDecimal detalleControlReversionPagoNuevo, Date detalleControlReversionFechaHora, boolean detalleControlReversionPagoEnColegio, String detalleControlReversionPagoObservacion, boolean detalleControlReversionPagoActivo) {
       this.detalleControlReversionId = detalleControlReversionId;
       this.controlPago = controlPago;
       this.detalleControlReversionPagoAnterior = detalleControlReversionPagoAnterior;
       this.detalleControlReversionPagoNuevo = detalleControlReversionPagoNuevo;
       this.detalleControlReversionFechaHora = detalleControlReversionFechaHora;
       this.detalleControlReversionPagoEnColegio = detalleControlReversionPagoEnColegio;
       this.detalleControlReversionPagoObservacion = detalleControlReversionPagoObservacion;
       this.detalleControlReversionPagoActivo = detalleControlReversionPagoActivo;
    }
   
    public int getDetalleControlReversionId() {
        return this.detalleControlReversionId;
    }
    
    public void setDetalleControlReversionId(int detalleControlReversionId) {
        this.detalleControlReversionId = detalleControlReversionId;
    }
    public ControlPago getControlPago() {
        return this.controlPago;
    }
    
    public void setControlPago(ControlPago controlPago) {
        this.controlPago = controlPago;
    }
    public BigDecimal getDetalleControlReversionPagoAnterior() {
        return this.detalleControlReversionPagoAnterior;
    }
    
    public void setDetalleControlReversionPagoAnterior(BigDecimal detalleControlReversionPagoAnterior) {
        this.detalleControlReversionPagoAnterior = detalleControlReversionPagoAnterior;
    }
    public BigDecimal getDetalleControlReversionPagoNuevo() {
        return this.detalleControlReversionPagoNuevo;
    }
    
    public void setDetalleControlReversionPagoNuevo(BigDecimal detalleControlReversionPagoNuevo) {
        this.detalleControlReversionPagoNuevo = detalleControlReversionPagoNuevo;
    }
    public Date getDetalleControlReversionFechaHora() {
        return this.detalleControlReversionFechaHora;
    }
    
    public void setDetalleControlReversionFechaHora(Date detalleControlReversionFechaHora) {
        this.detalleControlReversionFechaHora = detalleControlReversionFechaHora;
    }
    public boolean isDetalleControlReversionPagoEnColegio() {
        return this.detalleControlReversionPagoEnColegio;
    }
    
    public void setDetalleControlReversionPagoEnColegio(boolean detalleControlReversionPagoEnColegio) {
        this.detalleControlReversionPagoEnColegio = detalleControlReversionPagoEnColegio;
    }
    public String getDetalleControlReversionPagoObservacion() {
        return this.detalleControlReversionPagoObservacion;
    }
    
    public void setDetalleControlReversionPagoObservacion(String detalleControlReversionPagoObservacion) {
        this.detalleControlReversionPagoObservacion = detalleControlReversionPagoObservacion;
    }
    public boolean isDetalleControlReversionPagoActivo() {
        return this.detalleControlReversionPagoActivo;
    }
    
    public void setDetalleControlReversionPagoActivo(boolean detalleControlReversionPagoActivo) {
        this.detalleControlReversionPagoActivo = detalleControlReversionPagoActivo;
    }




}


