package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EspecialidadGrado generated by hbm2java
 */
public class EspecialidadGrado  implements java.io.Serializable {


     private int especialidadGradoId;
     private Serializable especialidadGradoNombre;
     private boolean especialidadGradoActivo;
     private Date especialidadGradoFechaModificacion;
     private Set<ConfiguracionGrado> configuracionGrados = new HashSet<ConfiguracionGrado>(0);

    public EspecialidadGrado() {
    }

	
    public EspecialidadGrado(int especialidadGradoId, Serializable especialidadGradoNombre, boolean especialidadGradoActivo, Date especialidadGradoFechaModificacion) {
        this.especialidadGradoId = especialidadGradoId;
        this.especialidadGradoNombre = especialidadGradoNombre;
        this.especialidadGradoActivo = especialidadGradoActivo;
        this.especialidadGradoFechaModificacion = especialidadGradoFechaModificacion;
    }
    public EspecialidadGrado(int especialidadGradoId, Serializable especialidadGradoNombre, boolean especialidadGradoActivo, Date especialidadGradoFechaModificacion, Set<ConfiguracionGrado> configuracionGrados) {
       this.especialidadGradoId = especialidadGradoId;
       this.especialidadGradoNombre = especialidadGradoNombre;
       this.especialidadGradoActivo = especialidadGradoActivo;
       this.especialidadGradoFechaModificacion = especialidadGradoFechaModificacion;
       this.configuracionGrados = configuracionGrados;
    }
   
    public int getEspecialidadGradoId() {
        return this.especialidadGradoId;
    }
    
    public void setEspecialidadGradoId(int especialidadGradoId) {
        this.especialidadGradoId = especialidadGradoId;
    }
    public Serializable getEspecialidadGradoNombre() {
        return this.especialidadGradoNombre;
    }
    
    public void setEspecialidadGradoNombre(Serializable especialidadGradoNombre) {
        this.especialidadGradoNombre = especialidadGradoNombre;
    }
    public boolean isEspecialidadGradoActivo() {
        return this.especialidadGradoActivo;
    }
    
    public void setEspecialidadGradoActivo(boolean especialidadGradoActivo) {
        this.especialidadGradoActivo = especialidadGradoActivo;
    }
    public Date getEspecialidadGradoFechaModificacion() {
        return this.especialidadGradoFechaModificacion;
    }
    
    public void setEspecialidadGradoFechaModificacion(Date especialidadGradoFechaModificacion) {
        this.especialidadGradoFechaModificacion = especialidadGradoFechaModificacion;
    }
    public Set<ConfiguracionGrado> getConfiguracionGrados() {
        return this.configuracionGrados;
    }
    
    public void setConfiguracionGrados(Set<ConfiguracionGrado> configuracionGrados) {
        this.configuracionGrados = configuracionGrados;
    }




}


