package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EstadoControlPago generated by hbm2java
 */
public class EstadoControlPago  implements java.io.Serializable {


     private int estadoControlPagoId;
     private Serializable estadoControlPagoNombre;
     private Serializable estadoControlPagoAlias;
     private Date estadoControlPagoFechaModificacion;
     private boolean estadoControlPagoActivo;
     private Set<ControlPago> controlPagos = new HashSet<ControlPago>(0);

    public EstadoControlPago() {
    }

	
    public EstadoControlPago(int estadoControlPagoId, Serializable estadoControlPagoNombre, Date estadoControlPagoFechaModificacion, boolean estadoControlPagoActivo) {
        this.estadoControlPagoId = estadoControlPagoId;
        this.estadoControlPagoNombre = estadoControlPagoNombre;
        this.estadoControlPagoFechaModificacion = estadoControlPagoFechaModificacion;
        this.estadoControlPagoActivo = estadoControlPagoActivo;
    }
    public EstadoControlPago(int estadoControlPagoId, Serializable estadoControlPagoNombre, Serializable estadoControlPagoAlias, Date estadoControlPagoFechaModificacion, boolean estadoControlPagoActivo, Set<ControlPago> controlPagos) {
       this.estadoControlPagoId = estadoControlPagoId;
       this.estadoControlPagoNombre = estadoControlPagoNombre;
       this.estadoControlPagoAlias = estadoControlPagoAlias;
       this.estadoControlPagoFechaModificacion = estadoControlPagoFechaModificacion;
       this.estadoControlPagoActivo = estadoControlPagoActivo;
       this.controlPagos = controlPagos;
    }
   
    public int getEstadoControlPagoId() {
        return this.estadoControlPagoId;
    }
    
    public void setEstadoControlPagoId(int estadoControlPagoId) {
        this.estadoControlPagoId = estadoControlPagoId;
    }
    public Serializable getEstadoControlPagoNombre() {
        return this.estadoControlPagoNombre;
    }
    
    public void setEstadoControlPagoNombre(Serializable estadoControlPagoNombre) {
        this.estadoControlPagoNombre = estadoControlPagoNombre;
    }
    public Serializable getEstadoControlPagoAlias() {
        return this.estadoControlPagoAlias;
    }
    
    public void setEstadoControlPagoAlias(Serializable estadoControlPagoAlias) {
        this.estadoControlPagoAlias = estadoControlPagoAlias;
    }
    public Date getEstadoControlPagoFechaModificacion() {
        return this.estadoControlPagoFechaModificacion;
    }
    
    public void setEstadoControlPagoFechaModificacion(Date estadoControlPagoFechaModificacion) {
        this.estadoControlPagoFechaModificacion = estadoControlPagoFechaModificacion;
    }
    public boolean isEstadoControlPagoActivo() {
        return this.estadoControlPagoActivo;
    }
    
    public void setEstadoControlPagoActivo(boolean estadoControlPagoActivo) {
        this.estadoControlPagoActivo = estadoControlPagoActivo;
    }
    public Set<ControlPago> getControlPagos() {
        return this.controlPagos;
    }
    
    public void setControlPagos(Set<ControlPago> controlPagos) {
        this.controlPagos = controlPagos;
    }




}


