package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Genero generated by hbm2java
 */
public class Genero  implements java.io.Serializable {


     private int generoId;
     private Serializable generoNombre;
     private boolean generoActivo;
     private Date generoFechaModificacion;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public Genero() {
    }

	
    public Genero(int generoId, Serializable generoNombre, boolean generoActivo, Date generoFechaModificacion) {
        this.generoId = generoId;
        this.generoNombre = generoNombre;
        this.generoActivo = generoActivo;
        this.generoFechaModificacion = generoFechaModificacion;
    }
    public Genero(int generoId, Serializable generoNombre, boolean generoActivo, Date generoFechaModificacion, Set<Persona> personas) {
       this.generoId = generoId;
       this.generoNombre = generoNombre;
       this.generoActivo = generoActivo;
       this.generoFechaModificacion = generoFechaModificacion;
       this.personas = personas;
    }
   
    public int getGeneroId() {
        return this.generoId;
    }
    
    public void setGeneroId(int generoId) {
        this.generoId = generoId;
    }
    public Serializable getGeneroNombre() {
        return this.generoNombre;
    }
    
    public void setGeneroNombre(Serializable generoNombre) {
        this.generoNombre = generoNombre;
    }
    public boolean isGeneroActivo() {
        return this.generoActivo;
    }
    
    public void setGeneroActivo(boolean generoActivo) {
        this.generoActivo = generoActivo;
    }
    public Date getGeneroFechaModificacion() {
        return this.generoFechaModificacion;
    }
    
    public void setGeneroFechaModificacion(Date generoFechaModificacion) {
        this.generoFechaModificacion = generoFechaModificacion;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


