package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Grado generated by hbm2java
 */
public class Grado  implements java.io.Serializable {


     private int gradoId;
     private NivelEstudio nivelEstudio;
     private Serializable gradoNombre;
     private boolean gradoActivo;
     private Date gradoFechaModificacion;
     private Set<ConfiguracionGrado> configuracionGrados = new HashSet<ConfiguracionGrado>(0);

    public Grado() {
    }

	
    public Grado(int gradoId, NivelEstudio nivelEstudio, Serializable gradoNombre, boolean gradoActivo, Date gradoFechaModificacion) {
        this.gradoId = gradoId;
        this.nivelEstudio = nivelEstudio;
        this.gradoNombre = gradoNombre;
        this.gradoActivo = gradoActivo;
        this.gradoFechaModificacion = gradoFechaModificacion;
    }
    public Grado(int gradoId, NivelEstudio nivelEstudio, Serializable gradoNombre, boolean gradoActivo, Date gradoFechaModificacion, Set<ConfiguracionGrado> configuracionGrados) {
       this.gradoId = gradoId;
       this.nivelEstudio = nivelEstudio;
       this.gradoNombre = gradoNombre;
       this.gradoActivo = gradoActivo;
       this.gradoFechaModificacion = gradoFechaModificacion;
       this.configuracionGrados = configuracionGrados;
    }
   
    public int getGradoId() {
        return this.gradoId;
    }
    
    public void setGradoId(int gradoId) {
        this.gradoId = gradoId;
    }
    public NivelEstudio getNivelEstudio() {
        return this.nivelEstudio;
    }
    
    public void setNivelEstudio(NivelEstudio nivelEstudio) {
        this.nivelEstudio = nivelEstudio;
    }
    public Serializable getGradoNombre() {
        return this.gradoNombre;
    }
    
    public void setGradoNombre(Serializable gradoNombre) {
        this.gradoNombre = gradoNombre;
    }
    public boolean isGradoActivo() {
        return this.gradoActivo;
    }
    
    public void setGradoActivo(boolean gradoActivo) {
        this.gradoActivo = gradoActivo;
    }
    public Date getGradoFechaModificacion() {
        return this.gradoFechaModificacion;
    }
    
    public void setGradoFechaModificacion(Date gradoFechaModificacion) {
        this.gradoFechaModificacion = gradoFechaModificacion;
    }
    public Set<ConfiguracionGrado> getConfiguracionGrados() {
        return this.configuracionGrados;
    }
    
    public void setConfiguracionGrados(Set<ConfiguracionGrado> configuracionGrados) {
        this.configuracionGrados = configuracionGrados;
    }




}


