package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * InstitucionParametro generated by hbm2java
 */
public class InstitucionParametro  implements java.io.Serializable {


     private int institucionParametroId;
     private AnioLectivo anioLectivo;
     private Serializable institucionParametroNombre;
     private Serializable institucionParametroDireccion;
     private Serializable institucionParametroUrlLogo;
     private boolean institucionParametroActivo;
     private Date institucionParametroFechaModificacion;
     private Serializable institucionUrlReporte;

    public InstitucionParametro() {
    }

	
    public InstitucionParametro(int institucionParametroId, AnioLectivo anioLectivo, Serializable institucionParametroNombre, Serializable institucionParametroDireccion, Serializable institucionParametroUrlLogo, boolean institucionParametroActivo, Date institucionParametroFechaModificacion) {
        this.institucionParametroId = institucionParametroId;
        this.anioLectivo = anioLectivo;
        this.institucionParametroNombre = institucionParametroNombre;
        this.institucionParametroDireccion = institucionParametroDireccion;
        this.institucionParametroUrlLogo = institucionParametroUrlLogo;
        this.institucionParametroActivo = institucionParametroActivo;
        this.institucionParametroFechaModificacion = institucionParametroFechaModificacion;
    }
    public InstitucionParametro(int institucionParametroId, AnioLectivo anioLectivo, Serializable institucionParametroNombre, Serializable institucionParametroDireccion, Serializable institucionParametroUrlLogo, boolean institucionParametroActivo, Date institucionParametroFechaModificacion, Serializable institucionUrlReporte) {
       this.institucionParametroId = institucionParametroId;
       this.anioLectivo = anioLectivo;
       this.institucionParametroNombre = institucionParametroNombre;
       this.institucionParametroDireccion = institucionParametroDireccion;
       this.institucionParametroUrlLogo = institucionParametroUrlLogo;
       this.institucionParametroActivo = institucionParametroActivo;
       this.institucionParametroFechaModificacion = institucionParametroFechaModificacion;
       this.institucionUrlReporte = institucionUrlReporte;
    }
   
    public int getInstitucionParametroId() {
        return this.institucionParametroId;
    }
    
    public void setInstitucionParametroId(int institucionParametroId) {
        this.institucionParametroId = institucionParametroId;
    }
    public AnioLectivo getAnioLectivo() {
        return this.anioLectivo;
    }
    
    public void setAnioLectivo(AnioLectivo anioLectivo) {
        this.anioLectivo = anioLectivo;
    }
    public Serializable getInstitucionParametroNombre() {
        return this.institucionParametroNombre;
    }
    
    public void setInstitucionParametroNombre(Serializable institucionParametroNombre) {
        this.institucionParametroNombre = institucionParametroNombre;
    }
    public Serializable getInstitucionParametroDireccion() {
        return this.institucionParametroDireccion;
    }
    
    public void setInstitucionParametroDireccion(Serializable institucionParametroDireccion) {
        this.institucionParametroDireccion = institucionParametroDireccion;
    }
    public Serializable getInstitucionParametroUrlLogo() {
        return this.institucionParametroUrlLogo;
    }
    
    public void setInstitucionParametroUrlLogo(Serializable institucionParametroUrlLogo) {
        this.institucionParametroUrlLogo = institucionParametroUrlLogo;
    }
    public boolean isInstitucionParametroActivo() {
        return this.institucionParametroActivo;
    }
    
    public void setInstitucionParametroActivo(boolean institucionParametroActivo) {
        this.institucionParametroActivo = institucionParametroActivo;
    }
    public Date getInstitucionParametroFechaModificacion() {
        return this.institucionParametroFechaModificacion;
    }
    
    public void setInstitucionParametroFechaModificacion(Date institucionParametroFechaModificacion) {
        this.institucionParametroFechaModificacion = institucionParametroFechaModificacion;
    }
    public Serializable getInstitucionUrlReporte() {
        return this.institucionUrlReporte;
    }
    
    public void setInstitucionUrlReporte(Serializable institucionUrlReporte) {
        this.institucionUrlReporte = institucionUrlReporte;
    }




}


