package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * LogCambioCuota generated by hbm2java
 */
public class LogCambioCuota  implements java.io.Serializable {


     private int logCambioCuotaId;
     private int controlPagoId;
     private int usuarioId;
     private BigDecimal logCambioValorOriginal;
     private BigDecimal logCambioValorNuevo;
     private Date logCambioFechaHora;

    public LogCambioCuota() {
    }

    public LogCambioCuota(int logCambioCuotaId, int controlPagoId, int usuarioId, BigDecimal logCambioValorOriginal, BigDecimal logCambioValorNuevo, Date logCambioFechaHora) {
       this.logCambioCuotaId = logCambioCuotaId;
       this.controlPagoId = controlPagoId;
       this.usuarioId = usuarioId;
       this.logCambioValorOriginal = logCambioValorOriginal;
       this.logCambioValorNuevo = logCambioValorNuevo;
       this.logCambioFechaHora = logCambioFechaHora;
    }
   
    public int getLogCambioCuotaId() {
        return this.logCambioCuotaId;
    }
    
    public void setLogCambioCuotaId(int logCambioCuotaId) {
        this.logCambioCuotaId = logCambioCuotaId;
    }
    public int getControlPagoId() {
        return this.controlPagoId;
    }
    
    public void setControlPagoId(int controlPagoId) {
        this.controlPagoId = controlPagoId;
    }
    public int getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }
    public BigDecimal getLogCambioValorOriginal() {
        return this.logCambioValorOriginal;
    }
    
    public void setLogCambioValorOriginal(BigDecimal logCambioValorOriginal) {
        this.logCambioValorOriginal = logCambioValorOriginal;
    }
    public BigDecimal getLogCambioValorNuevo() {
        return this.logCambioValorNuevo;
    }
    
    public void setLogCambioValorNuevo(BigDecimal logCambioValorNuevo) {
        this.logCambioValorNuevo = logCambioValorNuevo;
    }
    public Date getLogCambioFechaHora() {
        return this.logCambioFechaHora;
    }
    
    public void setLogCambioFechaHora(Date logCambioFechaHora) {
        this.logCambioFechaHora = logCambioFechaHora;
    }




}


