package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * LogInicioSesion generated by hbm2java
 */
public class LogInicioSesion  implements java.io.Serializable {


     private int logInicioSesionId;
     private Date logInicioSesionFechaHora;
     private Serializable logInicioSesionUsuario;
     private Serializable logInicioSesionPassword;
     private Serializable logInicioSesionDetalle;

    public LogInicioSesion() {
    }

    public LogInicioSesion(int logInicioSesionId, Date logInicioSesionFechaHora, Serializable logInicioSesionUsuario, Serializable logInicioSesionPassword, Serializable logInicioSesionDetalle) {
       this.logInicioSesionId = logInicioSesionId;
       this.logInicioSesionFechaHora = logInicioSesionFechaHora;
       this.logInicioSesionUsuario = logInicioSesionUsuario;
       this.logInicioSesionPassword = logInicioSesionPassword;
       this.logInicioSesionDetalle = logInicioSesionDetalle;
    }
   
    public int getLogInicioSesionId() {
        return this.logInicioSesionId;
    }
    
    public void setLogInicioSesionId(int logInicioSesionId) {
        this.logInicioSesionId = logInicioSesionId;
    }
    public Date getLogInicioSesionFechaHora() {
        return this.logInicioSesionFechaHora;
    }
    
    public void setLogInicioSesionFechaHora(Date logInicioSesionFechaHora) {
        this.logInicioSesionFechaHora = logInicioSesionFechaHora;
    }
    public Serializable getLogInicioSesionUsuario() {
        return this.logInicioSesionUsuario;
    }
    
    public void setLogInicioSesionUsuario(Serializable logInicioSesionUsuario) {
        this.logInicioSesionUsuario = logInicioSesionUsuario;
    }
    public Serializable getLogInicioSesionPassword() {
        return this.logInicioSesionPassword;
    }
    
    public void setLogInicioSesionPassword(Serializable logInicioSesionPassword) {
        this.logInicioSesionPassword = logInicioSesionPassword;
    }
    public Serializable getLogInicioSesionDetalle() {
        return this.logInicioSesionDetalle;
    }
    
    public void setLogInicioSesionDetalle(Serializable logInicioSesionDetalle) {
        this.logInicioSesionDetalle = logInicioSesionDetalle;
    }




}


