package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * LogPagoDb generated by hbm2java
 */
public class LogPagoDb  implements java.io.Serializable {


     private int logPagoDbid;
     private int usuarioId;
     private int controlPagoId;
     private Date logPagoFechaHora;
     private BigDecimal logPagoValorInicial;
     private BigDecimal logPagoValorIntroducido;
     private BigDecimal logPagoValorNuevo;

    public LogPagoDb() {
    }

    public LogPagoDb(int logPagoDbid, int usuarioId, int controlPagoId, Date logPagoFechaHora, BigDecimal logPagoValorInicial, BigDecimal logPagoValorIntroducido, BigDecimal logPagoValorNuevo) {
       this.logPagoDbid = logPagoDbid;
       this.usuarioId = usuarioId;
       this.controlPagoId = controlPagoId;
       this.logPagoFechaHora = logPagoFechaHora;
       this.logPagoValorInicial = logPagoValorInicial;
       this.logPagoValorIntroducido = logPagoValorIntroducido;
       this.logPagoValorNuevo = logPagoValorNuevo;
    }
   
    public int getLogPagoDbid() {
        return this.logPagoDbid;
    }
    
    public void setLogPagoDbid(int logPagoDbid) {
        this.logPagoDbid = logPagoDbid;
    }
    public int getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }
    public int getControlPagoId() {
        return this.controlPagoId;
    }
    
    public void setControlPagoId(int controlPagoId) {
        this.controlPagoId = controlPagoId;
    }
    public Date getLogPagoFechaHora() {
        return this.logPagoFechaHora;
    }
    
    public void setLogPagoFechaHora(Date logPagoFechaHora) {
        this.logPagoFechaHora = logPagoFechaHora;
    }
    public BigDecimal getLogPagoValorInicial() {
        return this.logPagoValorInicial;
    }
    
    public void setLogPagoValorInicial(BigDecimal logPagoValorInicial) {
        this.logPagoValorInicial = logPagoValorInicial;
    }
    public BigDecimal getLogPagoValorIntroducido() {
        return this.logPagoValorIntroducido;
    }
    
    public void setLogPagoValorIntroducido(BigDecimal logPagoValorIntroducido) {
        this.logPagoValorIntroducido = logPagoValorIntroducido;
    }
    public BigDecimal getLogPagoValorNuevo() {
        return this.logPagoValorNuevo;
    }
    
    public void setLogPagoValorNuevo(BigDecimal logPagoValorNuevo) {
        this.logPagoValorNuevo = logPagoValorNuevo;
    }




}


