package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NivelEstudio generated by hbm2java
 */
public class NivelEstudio  implements java.io.Serializable {


     private int nivelEstudioId;
     private Serializable nivelEstudioNombre;
     private boolean nivelEstudioActivo;
     private Date nivelEstudioFechaModificacion;
     private Set<Grado> grados = new HashSet<Grado>(0);

    public NivelEstudio() {
    }

	
    public NivelEstudio(int nivelEstudioId, Serializable nivelEstudioNombre, boolean nivelEstudioActivo, Date nivelEstudioFechaModificacion) {
        this.nivelEstudioId = nivelEstudioId;
        this.nivelEstudioNombre = nivelEstudioNombre;
        this.nivelEstudioActivo = nivelEstudioActivo;
        this.nivelEstudioFechaModificacion = nivelEstudioFechaModificacion;
    }
    public NivelEstudio(int nivelEstudioId, Serializable nivelEstudioNombre, boolean nivelEstudioActivo, Date nivelEstudioFechaModificacion, Set<Grado> grados) {
       this.nivelEstudioId = nivelEstudioId;
       this.nivelEstudioNombre = nivelEstudioNombre;
       this.nivelEstudioActivo = nivelEstudioActivo;
       this.nivelEstudioFechaModificacion = nivelEstudioFechaModificacion;
       this.grados = grados;
    }
   
    public int getNivelEstudioId() {
        return this.nivelEstudioId;
    }
    
    public void setNivelEstudioId(int nivelEstudioId) {
        this.nivelEstudioId = nivelEstudioId;
    }
    public Serializable getNivelEstudioNombre() {
        return this.nivelEstudioNombre;
    }
    
    public void setNivelEstudioNombre(Serializable nivelEstudioNombre) {
        this.nivelEstudioNombre = nivelEstudioNombre;
    }
    public boolean isNivelEstudioActivo() {
        return this.nivelEstudioActivo;
    }
    
    public void setNivelEstudioActivo(boolean nivelEstudioActivo) {
        this.nivelEstudioActivo = nivelEstudioActivo;
    }
    public Date getNivelEstudioFechaModificacion() {
        return this.nivelEstudioFechaModificacion;
    }
    
    public void setNivelEstudioFechaModificacion(Date nivelEstudioFechaModificacion) {
        this.nivelEstudioFechaModificacion = nivelEstudioFechaModificacion;
    }
    public Set<Grado> getGrados() {
        return this.grados;
    }
    
    public void setGrados(Set<Grado> grados) {
        this.grados = grados;
    }




}


