package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Permiso generated by hbm2java
 */
public class Permiso  implements java.io.Serializable {


     private int permisoId;
     private Serializable permisoCodigo;
     private Serializable permisoNombre;
     private boolean permisoActivo;
     private Date permisoFechaModificacion;
     private Set<RolPermiso> rolPermisos = new HashSet<RolPermiso>(0);

    public Permiso() {
    }

	
    public Permiso(int permisoId, Serializable permisoCodigo, Serializable permisoNombre, boolean permisoActivo, Date permisoFechaModificacion) {
        this.permisoId = permisoId;
        this.permisoCodigo = permisoCodigo;
        this.permisoNombre = permisoNombre;
        this.permisoActivo = permisoActivo;
        this.permisoFechaModificacion = permisoFechaModificacion;
    }
    public Permiso(int permisoId, Serializable permisoCodigo, Serializable permisoNombre, boolean permisoActivo, Date permisoFechaModificacion, Set<RolPermiso> rolPermisos) {
       this.permisoId = permisoId;
       this.permisoCodigo = permisoCodigo;
       this.permisoNombre = permisoNombre;
       this.permisoActivo = permisoActivo;
       this.permisoFechaModificacion = permisoFechaModificacion;
       this.rolPermisos = rolPermisos;
    }
   
    public int getPermisoId() {
        return this.permisoId;
    }
    
    public void setPermisoId(int permisoId) {
        this.permisoId = permisoId;
    }
    public Serializable getPermisoCodigo() {
        return this.permisoCodigo;
    }
    
    public void setPermisoCodigo(Serializable permisoCodigo) {
        this.permisoCodigo = permisoCodigo;
    }
    public Serializable getPermisoNombre() {
        return this.permisoNombre;
    }
    
    public void setPermisoNombre(Serializable permisoNombre) {
        this.permisoNombre = permisoNombre;
    }
    public boolean isPermisoActivo() {
        return this.permisoActivo;
    }
    
    public void setPermisoActivo(boolean permisoActivo) {
        this.permisoActivo = permisoActivo;
    }
    public Date getPermisoFechaModificacion() {
        return this.permisoFechaModificacion;
    }
    
    public void setPermisoFechaModificacion(Date permisoFechaModificacion) {
        this.permisoFechaModificacion = permisoFechaModificacion;
    }
    public Set<RolPermiso> getRolPermisos() {
        return this.rolPermisos;
    }
    
    public void setRolPermisos(Set<RolPermiso> rolPermisos) {
        this.rolPermisos = rolPermisos;
    }




}


