package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int personaId;
     private Genero genero;
     private Serializable personaNombre;
     private Serializable personaApellidos;
     private boolean personaActivo;
     private Date personaFechaModificacion;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Estudiante> estudiantes = new HashSet<Estudiante>(0);

    public Persona() {
    }

	
    public Persona(int personaId, Genero genero, Serializable personaNombre, Serializable personaApellidos, boolean personaActivo, Date personaFechaModificacion) {
        this.personaId = personaId;
        this.genero = genero;
        this.personaNombre = personaNombre;
        this.personaApellidos = personaApellidos;
        this.personaActivo = personaActivo;
        this.personaFechaModificacion = personaFechaModificacion;
    }
    public Persona(int personaId, Genero genero, Serializable personaNombre, Serializable personaApellidos, boolean personaActivo, Date personaFechaModificacion, Set<Usuario> usuarios, Set<Estudiante> estudiantes) {
       this.personaId = personaId;
       this.genero = genero;
       this.personaNombre = personaNombre;
       this.personaApellidos = personaApellidos;
       this.personaActivo = personaActivo;
       this.personaFechaModificacion = personaFechaModificacion;
       this.usuarios = usuarios;
       this.estudiantes = estudiantes;
    }
   
    public int getPersonaId() {
        return this.personaId;
    }
    
    public void setPersonaId(int personaId) {
        this.personaId = personaId;
    }
    public Genero getGenero() {
        return this.genero;
    }
    
    public void setGenero(Genero genero) {
        this.genero = genero;
    }
    public Serializable getPersonaNombre() {
        return this.personaNombre;
    }
    
    public void setPersonaNombre(Serializable personaNombre) {
        this.personaNombre = personaNombre;
    }
    public Serializable getPersonaApellidos() {
        return this.personaApellidos;
    }
    
    public void setPersonaApellidos(Serializable personaApellidos) {
        this.personaApellidos = personaApellidos;
    }
    public boolean isPersonaActivo() {
        return this.personaActivo;
    }
    
    public void setPersonaActivo(boolean personaActivo) {
        this.personaActivo = personaActivo;
    }
    public Date getPersonaFechaModificacion() {
        return this.personaFechaModificacion;
    }
    
    public void setPersonaFechaModificacion(Date personaFechaModificacion) {
        this.personaFechaModificacion = personaFechaModificacion;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<Estudiante> getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set<Estudiante> estudiantes) {
        this.estudiantes = estudiantes;
    }




}


