package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1



/**
 * Receptora generated by hbm2java
 */
public class Receptora  implements java.io.Serializable {


     private int id;
     private Integer valor;

    public Receptora() {
    }

	
    public Receptora(int id) {
        this.id = id;
    }
    public Receptora(int id, Integer valor) {
       this.id = id;
       this.valor = valor;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getValor() {
        return this.valor;
    }
    
    public void setValor(Integer valor) {
        this.valor = valor;
    }




}


