package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private int rolId;
     private Serializable rolNombre;
     private boolean rolActivo;
     private Date rolFechaModificacion;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<RolPermiso> rolPermisos = new HashSet<RolPermiso>(0);

    public Rol() {
    }

	
    public Rol(int rolId, Serializable rolNombre, boolean rolActivo, Date rolFechaModificacion) {
        this.rolId = rolId;
        this.rolNombre = rolNombre;
        this.rolActivo = rolActivo;
        this.rolFechaModificacion = rolFechaModificacion;
    }
    public Rol(int rolId, Serializable rolNombre, boolean rolActivo, Date rolFechaModificacion, Set<Usuario> usuarios, Set<RolPermiso> rolPermisos) {
       this.rolId = rolId;
       this.rolNombre = rolNombre;
       this.rolActivo = rolActivo;
       this.rolFechaModificacion = rolFechaModificacion;
       this.usuarios = usuarios;
       this.rolPermisos = rolPermisos;
    }
   
    public int getRolId() {
        return this.rolId;
    }
    
    public void setRolId(int rolId) {
        this.rolId = rolId;
    }
    public Serializable getRolNombre() {
        return this.rolNombre;
    }
    
    public void setRolNombre(Serializable rolNombre) {
        this.rolNombre = rolNombre;
    }
    public boolean isRolActivo() {
        return this.rolActivo;
    }
    
    public void setRolActivo(boolean rolActivo) {
        this.rolActivo = rolActivo;
    }
    public Date getRolFechaModificacion() {
        return this.rolFechaModificacion;
    }
    
    public void setRolFechaModificacion(Date rolFechaModificacion) {
        this.rolFechaModificacion = rolFechaModificacion;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<RolPermiso> getRolPermisos() {
        return this.rolPermisos;
    }
    
    public void setRolPermisos(Set<RolPermiso> rolPermisos) {
        this.rolPermisos = rolPermisos;
    }




}


