package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RolPermiso generated by hbm2java
 */
public class RolPermiso  implements java.io.Serializable {


     private int rolPermisoId;
     private Permiso permiso;
     private Rol rol;
     private boolean permitido;
     private boolean rolPermisoActivo;
     private Date rolPermisoFechaModificacion;

    public RolPermiso() {
    }

    public RolPermiso(int rolPermisoId, Permiso permiso, Rol rol, boolean permitido, boolean rolPermisoActivo, Date rolPermisoFechaModificacion) {
       this.rolPermisoId = rolPermisoId;
       this.permiso = permiso;
       this.rol = rol;
       this.permitido = permitido;
       this.rolPermisoActivo = rolPermisoActivo;
       this.rolPermisoFechaModificacion = rolPermisoFechaModificacion;
    }
   
    public int getRolPermisoId() {
        return this.rolPermisoId;
    }
    
    public void setRolPermisoId(int rolPermisoId) {
        this.rolPermisoId = rolPermisoId;
    }
    public Permiso getPermiso() {
        return this.permiso;
    }
    
    public void setPermiso(Permiso permiso) {
        this.permiso = permiso;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public boolean isPermitido() {
        return this.permitido;
    }
    
    public void setPermitido(boolean permitido) {
        this.permitido = permitido;
    }
    public boolean isRolPermisoActivo() {
        return this.rolPermisoActivo;
    }
    
    public void setRolPermisoActivo(boolean rolPermisoActivo) {
        this.rolPermisoActivo = rolPermisoActivo;
    }
    public Date getRolPermisoFechaModificacion() {
        return this.rolPermisoFechaModificacion;
    }
    
    public void setRolPermisoFechaModificacion(Date rolPermisoFechaModificacion) {
        this.rolPermisoFechaModificacion = rolPermisoFechaModificacion;
    }




}


