package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoBeca generated by hbm2java
 */
public class TipoBeca  implements java.io.Serializable {


     private int tipoBecaId;
     private Serializable tipoBecaNombre;
     private boolean tipoBecaActivo;
     private Boolean mostrarSolvencia;
     private Date tipoBecaFechaModificacion;
     private Set<Matricula> matriculas = new HashSet<Matricula>(0);

    public TipoBeca() {
    }

	
    public TipoBeca(int tipoBecaId, Serializable tipoBecaNombre, boolean tipoBecaActivo, Date tipoBecaFechaModificacion) {
        this.tipoBecaId = tipoBecaId;
        this.tipoBecaNombre = tipoBecaNombre;
        this.tipoBecaActivo = tipoBecaActivo;
        this.tipoBecaFechaModificacion = tipoBecaFechaModificacion;
    }
    public TipoBeca(int tipoBecaId, Serializable tipoBecaNombre, boolean tipoBecaActivo, Boolean mostrarSolvencia, Date tipoBecaFechaModificacion, Set<Matricula> matriculas) {
       this.tipoBecaId = tipoBecaId;
       this.tipoBecaNombre = tipoBecaNombre;
       this.tipoBecaActivo = tipoBecaActivo;
       this.mostrarSolvencia = mostrarSolvencia;
       this.tipoBecaFechaModificacion = tipoBecaFechaModificacion;
       this.matriculas = matriculas;
    }
   
    public int getTipoBecaId() {
        return this.tipoBecaId;
    }
    
    public void setTipoBecaId(int tipoBecaId) {
        this.tipoBecaId = tipoBecaId;
    }
    public Serializable getTipoBecaNombre() {
        return this.tipoBecaNombre;
    }
    
    public void setTipoBecaNombre(Serializable tipoBecaNombre) {
        this.tipoBecaNombre = tipoBecaNombre;
    }
    public boolean isTipoBecaActivo() {
        return this.tipoBecaActivo;
    }
    
    public void setTipoBecaActivo(boolean tipoBecaActivo) {
        this.tipoBecaActivo = tipoBecaActivo;
    }
    public Boolean getMostrarSolvencia() {
        return this.mostrarSolvencia;
    }
    
    public void setMostrarSolvencia(Boolean mostrarSolvencia) {
        this.mostrarSolvencia = mostrarSolvencia;
    }
    public Date getTipoBecaFechaModificacion() {
        return this.tipoBecaFechaModificacion;
    }
    
    public void setTipoBecaFechaModificacion(Date tipoBecaFechaModificacion) {
        this.tipoBecaFechaModificacion = tipoBecaFechaModificacion;
    }
    public Set<Matricula> getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set<Matricula> matriculas) {
        this.matriculas = matriculas;
    }




}


