package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * TmpPc generated by hbm2java
 */
public class TmpPc  implements java.io.Serializable {


     private int codPc;
     private Serializable userId;
     private Serializable mensualidad;
     private Long cantidad;
     private Integer controlPagoId;
     private Date fecha;

    public TmpPc() {
    }

	
    public TmpPc(int codPc) {
        this.codPc = codPc;
    }
    public TmpPc(int codPc, Serializable userId, Serializable mensualidad, Long cantidad, Integer controlPagoId, Date fecha) {
       this.codPc = codPc;
       this.userId = userId;
       this.mensualidad = mensualidad;
       this.cantidad = cantidad;
       this.controlPagoId = controlPagoId;
       this.fecha = fecha;
    }
   
    public int getCodPc() {
        return this.codPc;
    }
    
    public void setCodPc(int codPc) {
        this.codPc = codPc;
    }
    public Serializable getUserId() {
        return this.userId;
    }
    
    public void setUserId(Serializable userId) {
        this.userId = userId;
    }
    public Serializable getMensualidad() {
        return this.mensualidad;
    }
    
    public void setMensualidad(Serializable mensualidad) {
        this.mensualidad = mensualidad;
    }
    public Long getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Long cantidad) {
        this.cantidad = cantidad;
    }
    public Integer getControlPagoId() {
        return this.controlPagoId;
    }
    
    public void setControlPagoId(Integer controlPagoId) {
        this.controlPagoId = controlPagoId;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


