package model;
// Generated 10-10-2020 10:11:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int usuarioId;
     private Persona persona;
     private Rol rol;
     private Serializable usuarioNombre;
     private Serializable usuarioPassword;
     private boolean usuarioActivo;
     private Date usuarioFechaModificacion;
     private Set<DetalleAsignacionCuota> detalleAsignacionCuotas = new HashSet<DetalleAsignacionCuota>(0);
     private Set<ArancelMatricula> arancelMatriculas = new HashSet<ArancelMatricula>(0);
     private Set<ControlPago> controlPagos = new HashSet<ControlPago>(0);

    public Usuario() {
    }

	
    public Usuario(int usuarioId, Persona persona, Rol rol, Serializable usuarioNombre, Serializable usuarioPassword, boolean usuarioActivo, Date usuarioFechaModificacion) {
        this.usuarioId = usuarioId;
        this.persona = persona;
        this.rol = rol;
        this.usuarioNombre = usuarioNombre;
        this.usuarioPassword = usuarioPassword;
        this.usuarioActivo = usuarioActivo;
        this.usuarioFechaModificacion = usuarioFechaModificacion;
    }
    public Usuario(int usuarioId, Persona persona, Rol rol, Serializable usuarioNombre, Serializable usuarioPassword, boolean usuarioActivo, Date usuarioFechaModificacion, Set<DetalleAsignacionCuota> detalleAsignacionCuotas, Set<ArancelMatricula> arancelMatriculas, Set<ControlPago> controlPagos) {
       this.usuarioId = usuarioId;
       this.persona = persona;
       this.rol = rol;
       this.usuarioNombre = usuarioNombre;
       this.usuarioPassword = usuarioPassword;
       this.usuarioActivo = usuarioActivo;
       this.usuarioFechaModificacion = usuarioFechaModificacion;
       this.detalleAsignacionCuotas = detalleAsignacionCuotas;
       this.arancelMatriculas = arancelMatriculas;
       this.controlPagos = controlPagos;
    }
   
    public int getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Serializable getUsuarioNombre() {
        return this.usuarioNombre;
    }
    
    public void setUsuarioNombre(Serializable usuarioNombre) {
        this.usuarioNombre = usuarioNombre;
    }
    public Serializable getUsuarioPassword() {
        return this.usuarioPassword;
    }
    
    public void setUsuarioPassword(Serializable usuarioPassword) {
        this.usuarioPassword = usuarioPassword;
    }
    public boolean isUsuarioActivo() {
        return this.usuarioActivo;
    }
    
    public void setUsuarioActivo(boolean usuarioActivo) {
        this.usuarioActivo = usuarioActivo;
    }
    public Date getUsuarioFechaModificacion() {
        return this.usuarioFechaModificacion;
    }
    
    public void setUsuarioFechaModificacion(Date usuarioFechaModificacion) {
        this.usuarioFechaModificacion = usuarioFechaModificacion;
    }
    public Set<DetalleAsignacionCuota> getDetalleAsignacionCuotas() {
        return this.detalleAsignacionCuotas;
    }
    
    public void setDetalleAsignacionCuotas(Set<DetalleAsignacionCuota> detalleAsignacionCuotas) {
        this.detalleAsignacionCuotas = detalleAsignacionCuotas;
    }
    public Set<ArancelMatricula> getArancelMatriculas() {
        return this.arancelMatriculas;
    }
    
    public void setArancelMatriculas(Set<ArancelMatricula> arancelMatriculas) {
        this.arancelMatriculas = arancelMatriculas;
    }
    public Set<ControlPago> getControlPagos() {
        return this.controlPagos;
    }
    
    public void setControlPagos(Set<ControlPago> controlPagos) {
        this.controlPagos = controlPagos;
    }




}


